import { notFound, redirect } from "next/navigation";
import { getCurrentChurchUser, canViewGiving, getCurrentChurch } from "@/lib/data/church";
import { getMemberDetail } from "@/lib/data/members";
import { getMemberGivingInRange } from "@/lib/data/giving";
import { formatCurrency, formatDate } from "@/lib/format";
import { GIVING_METHOD_LABELS, type GivingMethod } from "@/lib/validation/giving";
import { StatementPrintButton } from "@/components/giving/statement-print-button";
import { StatementDateRangeForm } from "@/components/giving/statement-date-range-form";

export default async function MemberStatementPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ from?: string; to?: string }>;
}) {
  const { id } = await params;
  const { from, to } = await searchParams;

  const churchUser = await getCurrentChurchUser();
  if (!churchUser) redirect("/onboarding");

  if (!canViewGiving(churchUser.role)) {
    return (
      <div className="py-10 text-center">
        <p className="text-base text-muted-foreground">
          Only admins and pastors can generate giving statements.
        </p>
      </div>
    );
  }

  const [member, church, records] = await Promise.all([
    getMemberDetail(id),
    getCurrentChurch(),
    getMemberGivingInRange(id, from, to),
  ]);

  if (!member) notFound();

  const total = records.reduce((sum, record) => sum + Number(record.amount), 0);
  const generatedOn = new Date().toLocaleDateString("en-GH", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="space-y-6 print:space-y-4">
      <StatementDateRangeForm from={from} to={to} />

      <div className="rounded-2xl border border-border bg-card p-6 print:rounded-none print:border-none print:p-0">
        <div className="flex items-start justify-between gap-4 border-b border-border pb-4">
          <div>
            <h1 className="text-xl font-semibold text-foreground">{church?.name ?? "Your Church"}</h1>
            <p className="text-sm text-muted-foreground">Giving Statement</p>
          </div>
          <p className="text-sm text-muted-foreground">Generated {generatedOn}</p>
        </div>

        <div className="mt-4">
          <p className="text-lg font-medium text-foreground">
            {member.first_name} {member.last_name}
          </p>
          <p className="text-sm text-muted-foreground">
            {from || to
              ? `${from ? formatDate(from) : "Start"} – ${to ? formatDate(to) : "Today"}`
              : "All-time"}
          </p>
        </div>

        <table className="mt-4 w-full text-left text-sm">
          <thead>
            <tr className="border-b border-border">
              <th className="py-2 font-medium text-muted-foreground">Date</th>
              <th className="py-2 font-medium text-muted-foreground">Fund</th>
              <th className="py-2 font-medium text-muted-foreground">Method</th>
              <th className="py-2 text-right font-medium text-muted-foreground">Amount</th>
            </tr>
          </thead>
          <tbody>
            {records.map((record) => (
              <tr key={record.id} className="border-b border-border">
                <td className="py-2 text-foreground">{formatDate(record.given_at)}</td>
                <td className="py-2 text-foreground">{record.fund?.name ?? "Giving"}</td>
                <td className="py-2 text-foreground">
                  {GIVING_METHOD_LABELS[record.method as GivingMethod] ?? record.method}
                </td>
                <td className="py-2 text-right text-foreground">
                  {formatCurrency(Number(record.amount), record.currency)}
                </td>
              </tr>
            ))}
            {records.length === 0 && (
              <tr>
                <td colSpan={4} className="py-6 text-center text-muted-foreground">
                  No giving records in this range.
                </td>
              </tr>
            )}
          </tbody>
          <tfoot>
            <tr>
              <td colSpan={3} className="pt-3 text-right font-semibold text-foreground">
                Total
              </td>
              <td className="pt-3 text-right font-semibold text-foreground">
                {formatCurrency(total, records[0]?.currency ?? "GHS")}
              </td>
            </tr>
          </tfoot>
        </table>

        <p className="mt-6 text-xs text-muted-foreground">
          Generated by FlockLine on {generatedOn}.
        </p>
      </div>

      <StatementPrintButton />
    </div>
  );
}
